# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x07hllm.v1\"\x07\n\x05\x45mpty\"/\n\x0f\x41rtifactVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\"S\n\x0cRuntimeError\x12 \n\x04\x63ode\x18\x01 \x01(\x0e\x32\x12.hllm.v1.ErrorCode\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x11\n\tretryable\x18\x03 \x01(\x08*\x9c\x02\n\x08\x44\x61taType\x12\x19\n\x15\x44\x41TA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x44\x41TA_TYPE_BOOL\x10\x01\x12\x10\n\x0c\x44\x41TA_TYPE_U8\x10\x02\x12\x10\n\x0c\x44\x41TA_TYPE_I8\x10\x03\x12\x11\n\rDATA_TYPE_I16\x10\x04\x12\x11\n\rDATA_TYPE_U16\x10\x05\x12\x11\n\rDATA_TYPE_I32\x10\x06\x12\x11\n\rDATA_TYPE_U32\x10\x07\x12\x11\n\rDATA_TYPE_I64\x10\x08\x12\x11\n\rDATA_TYPE_U64\x10\t\x12\x11\n\rDATA_TYPE_F16\x10\n\x12\x12\n\x0e\x44\x41TA_TYPE_BF16\x10\x0b\x12\x11\n\rDATA_TYPE_F32\x10\x0c\x12\x11\n\rDATA_TYPE_F64\x10\r*\x91\x01\n\nProvenance\x12\x1a\n\x16PROVENANCE_UNSPECIFIED\x10\x00\x12\x1a\n\x16PROVENANCE_THEORETICAL\x10\x01\x12\x19\n\x15PROVENANCE_CONFIGURED\x10\x02\x12\x17\n\x13PROVENANCE_OBSERVED\x10\x03\x12\x17\n\x13PROVENANCE_MEASURED\x10\x04*\xcf\x02\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x45RROR_CODE_INVALID_REQUEST\x10\x01\x12\"\n\x1e\x45RROR_CODE_INCOMPATIBLE_WORKER\x10\x02\x12\x1f\n\x1b\x45RROR_CODE_STALE_DEPLOYMENT\x10\x03\x12\x1b\n\x17\x45RROR_CODE_OUT_OF_ORDER\x10\x04\x12!\n\x1d\x45RROR_CODE_RESOURCE_EXHAUSTED\x10\x05\x12 \n\x1c\x45RROR_CODE_DEADLINE_EXCEEDED\x10\x06\x12!\n\x1d\x45RROR_CODE_WORKER_UNAVAILABLE\x10\x07\x12\x1c\n\x18\x45RROR_CODE_BACKEND_ERROR\x10\x08\x12\x1e\n\x1a\x45RROR_CODE_TRANSPORT_ERROR\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=169
  _globals['_DATATYPE']._serialized_end=453
  _globals['_PROVENANCE']._serialized_start=456
  _globals['_PROVENANCE']._serialized_end=601
  _globals['_ERRORCODE']._serialized_start=604
  _globals['_ERRORCODE']._serialized_end=939
  _globals['_EMPTY']._serialized_start=25
  _globals['_EMPTY']._serialized_end=32
  _globals['_ARTIFACTVERSION']._serialized_start=34
  _globals['_ARTIFACTVERSION']._serialized_end=81
  _globals['_RUNTIMEERROR']._serialized_start=83
  _globals['_RUNTIMEERROR']._serialized_end=166
# @@protoc_insertion_point(module_scope)
