# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import control_pb2 as control__pb2
from . import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/hllm.v1.WorkerControl/GetCapabilities',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.Capabilities.FromString,
                _registered_method=True)
        self.GetQualificationState = channel.unary_unary(
                '/hllm.v1.WorkerControl/GetQualificationState',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.QualificationState.FromString,
                _registered_method=True)
        self.GetLinkProbeInfo = channel.unary_unary(
                '/hllm.v1.WorkerControl/GetLinkProbeInfo',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=profile__pb2.LinkProbeIdentity.FromString,
                _registered_method=True)
        self.QualifyLink = channel.unary_unary(
                '/hllm.v1.WorkerControl/QualifyLink',
                request_serializer=control__pb2.LinkQualificationRequest.SerializeToString,
                response_deserializer=profile__pb2.LinkProfile.FromString,
                _registered_method=True)
        self.LoadStage = channel.unary_unary(
                '/hllm.v1.WorkerControl/LoadStage',
                request_serializer=control__pb2.LoadStageRequest.SerializeToString,
                response_deserializer=control__pb2.LoadStageResponse.FromString,
                _registered_method=True)
        self.UnloadStage = channel.unary_unary(
                '/hllm.v1.WorkerControl/UnloadStage',
                request_serializer=control__pb2.UnloadStageRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.ReserveRequest = channel.unary_unary(
                '/hllm.v1.WorkerControl/ReserveRequest',
                request_serializer=control__pb2.ReserveRequestMessage.SerializeToString,
                response_deserializer=control__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/hllm.v1.WorkerControl/CancelRequest',
                request_serializer=control__pb2.CancelRequestMessage.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMemoryReport = channel.unary_unary(
                '/hllm.v1.WorkerControl/GetMemoryReport',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.MemoryReport.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/hllm.v1.WorkerControl/GetMetrics',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.WorkerMetrics.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/hllm.v1.WorkerControl/Health',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.HealthResponse.FromString,
                _registered_method=True)


class WorkerControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQualificationState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkProbeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QualifyLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=control__pb2.Capabilities.SerializeToString,
            ),
            'GetQualificationState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQualificationState,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=control__pb2.QualificationState.SerializeToString,
            ),
            'GetLinkProbeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinkProbeInfo,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=profile__pb2.LinkProbeIdentity.SerializeToString,
            ),
            'QualifyLink': grpc.unary_unary_rpc_method_handler(
                    servicer.QualifyLink,
                    request_deserializer=control__pb2.LinkQualificationRequest.FromString,
                    response_serializer=profile__pb2.LinkProfile.SerializeToString,
            ),
            'LoadStage': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadStage,
                    request_deserializer=control__pb2.LoadStageRequest.FromString,
                    response_serializer=control__pb2.LoadStageResponse.SerializeToString,
            ),
            'UnloadStage': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadStage,
                    request_deserializer=control__pb2.UnloadStageRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'ReserveRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveRequest,
                    request_deserializer=control__pb2.ReserveRequestMessage.FromString,
                    response_serializer=control__pb2.ReserveResponse.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=control__pb2.CancelRequestMessage.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'GetMemoryReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryReport,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=control__pb2.MemoryReport.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=control__pb2.WorkerMetrics.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=control__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hllm.v1.WorkerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hllm.v1.WorkerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/GetCapabilities',
            common__pb2.Empty.SerializeToString,
            control__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQualificationState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/GetQualificationState',
            common__pb2.Empty.SerializeToString,
            control__pb2.QualificationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkProbeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/GetLinkProbeInfo',
            common__pb2.Empty.SerializeToString,
            profile__pb2.LinkProbeIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QualifyLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/QualifyLink',
            control__pb2.LinkQualificationRequest.SerializeToString,
            profile__pb2.LinkProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/LoadStage',
            control__pb2.LoadStageRequest.SerializeToString,
            control__pb2.LoadStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/UnloadStage',
            control__pb2.UnloadStageRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/ReserveRequest',
            control__pb2.ReserveRequestMessage.SerializeToString,
            control__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/CancelRequest',
            control__pb2.CancelRequestMessage.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/GetMemoryReport',
            common__pb2.Empty.SerializeToString,
            control__pb2.MemoryReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/GetMetrics',
            common__pb2.Empty.SerializeToString,
            control__pb2.WorkerMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hllm.v1.WorkerControl/Health',
            common__pb2.Empty.SerializeToString,
            control__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
