# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/hllm.v1.Generation/Generate',
                request_serializer=execution__pb2.GenerationRequest.SerializeToString,
                response_deserializer=execution__pb2.GenerationEvent.FromString,
                _registered_method=True)


class GenerationServicer:
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=execution__pb2.GenerationRequest.FromString,
                    response_serializer=execution__pb2.GenerationEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hllm.v1.Generation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hllm.v1.Generation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Generation:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hllm.v1.Generation/Generate',
            execution__pb2.GenerationRequest.SerializeToString,
            execution__pb2.GenerationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StageExecutionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.stream_stream(
                '/hllm.v1.StageExecution/Execute',
                request_serializer=execution__pb2.StageMessage.SerializeToString,
                response_deserializer=execution__pb2.StageMessage.FromString,
                _registered_method=True)


class StageExecutionServicer:
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StageExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.stream_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=execution__pb2.StageMessage.FromString,
                    response_serializer=execution__pb2.StageMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hllm.v1.StageExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hllm.v1.StageExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StageExecution:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hllm.v1.StageExecution/Execute',
            execution__pb2.StageMessage.SerializeToString,
            execution__pb2.StageMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
