# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: placement.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'placement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import profile_pb2 as profile__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fplacement.proto\x12\x07hllm.v1\x1a\x0c\x63ommon.proto\x1a\rprofile.proto\"\xba\x02\n\x0bStageMemory\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12%\n\x06\x64omain\x18\x02 \x01(\x0e\x32\x15.hllm.v1.MemoryDomain\x12\x13\n\x0blayer_start\x18\x03 \x01(\r\x12\x11\n\tlayer_end\x18\x04 \x01(\r\x12\x14\n\x0cweight_bytes\x18\x05 \x01(\x04\x12\x16\n\x0ekv_cache_bytes\x18\x06 \x01(\x04\x12\x17\n\x0fworkspace_bytes\x18\x07 \x01(\x04\x12\x1f\n\x17\x61\x63tivation_buffer_bytes\x18\x08 \x01(\x04\x12!\n\x19\x61llocator_allowance_bytes\x18\t \x01(\x04\x12\x16\n\x0erequired_bytes\x18\n \x01(\x04\x12\x14\n\x0cusable_bytes\x18\x0b \x01(\x04\x12\x10\n\x08pressure\x18\x0c \x01(\x01\"\xc5\x01\n\x0fStageAssignment\x12\x13\n\x0bstage_index\x18\x01 \x01(\r\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x13\n\x0blayer_start\x18\x03 \x01(\r\x12\x11\n\tlayer_end\x18\x04 \x01(\r\x12\x1c\n\x14owns_token_embedding\x18\x05 \x01(\x08\x12\x17\n\x0fowns_final_norm\x18\x06 \x01(\x08\x12\x14\n\x0cowns_lm_head\x18\x07 \x01(\x08\x12\x15\n\rowns_sampling\x18\x08 \x01(\x08\"\xbb\x03\n\x0e\x44\x65ploymentPlan\x12\x30\n\x0eschema_version\x18\x01 \x01(\x0b\x32\x18.hllm.v1.ArtifactVersion\x12\x17\n\x0fplanner_version\x18\x02 \x01(\t\x12\x0f\n\x07plan_id\x18\x03 \x01(\t\x12\x13\n\x0bplan_digest\x18\x04 \x01(\t\x12\x17\n\x0fmanifest_digest\x18\x05 \x01(\t\x12\x13\n\x0bworkload_id\x18\x06 \x01(\t\x12\x15\n\rplanning_mode\x18\x07 \x01(\t\x12*\n\x0f\x65xecution_dtype\x18\x08 \x01(\x0e\x32\x11.hllm.v1.DataType\x12+\n\x10\x61\x63tivation_dtype\x18\t \x01(\x0e\x32\x11.hllm.v1.DataType\x12\x13\n\x0bsplit_layer\x18\n \x01(\r\x12(\n\x06stages\x18\x0b \x03(\x0b\x32\x18.hllm.v1.StageAssignment\x12\x1d\n\x15selected_candidate_id\x18\x0c \x01(\t\x12 \n\x18\x64uplicated_tensor_groups\x18\r \x03(\t\x12\x1a\n\x12\x64\x65ployment_version\x18\x0e \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'placement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAGEMEMORY']._serialized_start=58
  _globals['_STAGEMEMORY']._serialized_end=372
  _globals['_STAGEASSIGNMENT']._serialized_start=375
  _globals['_STAGEASSIGNMENT']._serialized_end=572
  _globals['_DEPLOYMENTPLAN']._serialized_start=575
  _globals['_DEPLOYMENTPLAN']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
